from typing import Generic, TypeVar


MODEL_SCHEMA = TypeVar("MODEL_SCHEMA")
RESPONSE_SCHEMA = TypeVar("RESPONSE_SCHEMA")
CREATE_SCHEMA = TypeVar("CREATE_SCHEMA")
DEPENDENCIES = TypeVar("DEPENDENCIES")
UPDATE_SCHEMA = TypeVar("UPDATE_SCHEMA")
